name: Deploy to Sandbox

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-cli-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install

      - name: Authenticate with Salesforce
        run: |
          echo ${{ secrets.SALESFORCE_USERNAME }} | sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile <path/to/server.key> --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername --setalias sandbox

      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy --sourcepath <path/to/metadata> --targetusername sandbox
