name: Deploy to Sandbox

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
            
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-cli-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install
# sfdx force:source:deploy --manifest=manifest/package.xml --testlevel=RunLocalTests -u kourim2570-v2az@force.com
      - name: echo key
        run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      - name: Authenticate with Salesforce
        run: | 
          sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername --setalias devjwt
          

       
# force:source:deploy,--manifest,manifest/package.xml,--targetusername,DevHub_Instance,--wait,30,--json,--ignorewarnings,--testlevel,RunLocalTests
      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -x manifest/package.xml --json --testlevel RunLocalTests --ignorewarnings -u ${{ secrets.SALESFORCE_USERNAME }}
