name: Deploy to Sandbox

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-cli-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install
# sfdx force:source:deploy --manifest=manifest/package.xml --testlevel=RunLocalTests -u kourim2570-v2az@force.com
      - name: Authenticate with Salesforce
        run: | 
          sfdx force:auth:jwt:grant --clientid=3MVG9CecKwYCDceSQnAaMpMKFXdGV.At_wliCAV4ShAOuRv0lcGYU9A5Qz1T9sMwKRz8BjssjohhoYBJh6XN9 --jwtkeyfile=server.key --username=kourim2570-v2az@force.com --setdefaultdevhubusername --setalias devjwt
          

       
# force:source:deploy,--manifest,manifest/package.xml,--targetusername,DevHub_Instance,--wait,30,--json,--ignorewarnings,--testlevel,RunLocalTests
      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -x manifest/package.xml --targetusername DevHub_Instance --json --testlevel RunLocalTests --ignorewarnings
